# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba82efd43a59c97bbc2b0a02624516aa20761b264ea08b1b793f393949a88ff54d496ac9b5b524df3a4db39b1fb514514c73a724b2d02aef3f8a9cc18c1eb06

test:
  secret_key_base: 90757b09844ff69b71a81e2efb55771e89c9a6d72d1200bd1a7bb53e3ba0fbd19522ecc020188cb36f9b1800c7cdfb2553ebe02fc55ec4e6eb7ab0e3471c483a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
